/**
 * recipes.ts — Auto-generated recipe data layer
 *
 * Source: Kaggle Indian Food datasets, processed by scripts/build_recipes.py
 * Do NOT edit this file manually. Regenerate with:
 *   python3 scripts/build_recipes.py
 *
 * To update with live Kaggle data:
 *   1. Create ~/.kaggle/kaggle.json (get token at https://www.kaggle.com/account)
 *   2. Run: python3 scripts/build_recipes.py
 *   3. Commit the updated data/recipes.json
 */
import type { Recipe } from '@/types';
import recipesJson from './recipes.json';

export const recipes: Recipe[] = recipesJson as Recipe[];

/** Quick lookup by recipe slug ID */
export const recipeById = new Map<string, Recipe>(
  recipes.map((r) => [r.id, r])
);

/** Total recipe count */
export const totalRecipeCount = recipes.length;
